# Generated by Django 3.0.7 on 2020-06-10 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='outset.Content')),
                ('description', models.TextField(blank=True, default='', max_length=40000, null=True)),
                ('data_source', models.CharField(blank=True, default='NONE', max_length=400)),
                ('url_key', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
