# Generated by Django 3.0.7 on 2020-06-14 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('name', models.CharField(max_length=400)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='outset.Content')),
                ('description', models.TextField(blank=True, default='', max_length=40000, null=True)),
                ('data_source', models.CharField(blank=True, default='NONE', max_length=400)),
                ('url_key', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_position', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stream.Video')),
            ],
        ),
        migrations.CreateModel(
            name='WatchingRecord',
            fields=[
                ('watch_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='video_stream.WatchHistory')),
                ('last_modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user_email', models.EmailField(help_text='Please add the email of your friend you want to invite.', max_length=254, verbose_name="Friend's email")),
                ('to_user_phone_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Please add the contact number of your friend you want to invite.', max_length=128, region=None, verbose_name="Friend's contact number")),
                ('message', models.CharField(default='Hey, I am on Gazelo and inviting you to join. It is AWESOME!!', max_length=400)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
