# Generated by Django 3.0.7 on 2020-06-11 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_position', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_stream.Video')),
            ],
        ),
        migrations.CreateModel(
            name='WatchingRecord',
            fields=[
                ('watch_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='video_stream.WatchHistory')),
                ('last_modified_timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
