# Generated by Django 3.0.7 on 2020-06-08 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('full_name', models.CharField(max_length=400)),
                ('email', models.CharField(blank=True, max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('videos_count', models.IntegerField()),
                ('followers_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('auth_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, default='', max_length=40000, null=True)),
                ('data_source', models.CharField(blank=True, default='NONE', max_length=400)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now_add=True)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('access_level', models.IntegerField(choices=[(0, 'Private, nobody can view'), (1, 'Only followers can view'), (2, 'Public, anybody can view')], default=0)),
                ('url_key', models.CharField(max_length=10)),
                ('size', models.IntegerField()),
                ('views_count', models.IntegerField()),
                ('likes_count', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('allow_comments', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='outset.User')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_view_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_by', to='outset.User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outset.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='outset.User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outset.Video')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='outset.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outset.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('is_top_level', models.BooleanField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='outset.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='outset.User')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outset.Video')),
            ],
        ),
    ]
