# Generated by Django 3.0.7 on 2020-06-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
