# Generated by Django 3.0.7 on 2020-06-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='data_source',
            field=models.CharField(default='NONE', max_length=400),
        ),
    ]
