# Generated by Django 3.0.7 on 2020-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outset', '0002_video_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='data_source',
            field=models.CharField(blank=True, default='NONE', max_length=400),
        ),
    ]
