# Generated by Django 3.0.7 on 2020-06-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outset', '0003_auto_20200607_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='following',
            old_name='following',
            new_name='follower',
        ),
    ]
