# Generated by Django 3.0.7 on 2020-06-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outset', '0004_auto_20200608_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='allow_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, default='', max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
